[project]
name = "steamdb-mcp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "beautifulsoup4>=4.13.4",
    "mcp[cli]>=1.10.1",
    "pandas>=2.3.1",
    "seleniumbase>=4.40.4",
]
